### ISSUE TITLE
description about metadata files

### ISSUE THREAD

**Issue by xx789633** [cloud-olap/FlexPushdownDB-old#6]
Hi @cloud-olap @Yifei-yang7 is there a doc describing the metadata files? For example, in directory "normal-ssb/metadata/ssb-sf1-sortlineorder/csv/", there are many metadata files, what do those files mean and how can we generate such files if we would like to use our own dataset? It seems those files are required to run FlexPushDownDB correctly.

**Comment by Yifei-yang7** [comment]
Hi, unfortunately we don't have a doc for that. But you can follow the same format to manually create them for your own dataset, which are majorly schema info and some statistics of your dataset. Segment_info is not needed unless you wish to run Belady caching policy.
